version: '3.8'
services:
  movies:
    image: sudheer374/sudmoies:v2
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: sudheer374/suddth:v2
    ports:
      - "83:80"
    deploy:
      replicas: 3

